import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type IngredientDef = [
  id: string,
  nameEn: string,
  nameZh: string,
  category: string,
  emoji: string,
  flavors: string[],
  aliases: string[],
];

const INGREDIENTS: IngredientDef[] = [
  // --- Spirits ---
  ["gin", "Gin", "金酒", "spirit", "🍸", ["botanical", "dry", "strong"], ["gin", "金酒", "琴酒", "杜松子酒"]],
  ["vodka", "Vodka", "伏特加", "spirit", "🍾", ["dry", "strong"], ["vodka", "伏特加"]],
  ["white_rum", "White Rum", "白朗姆酒", "spirit", "🥃", ["sweet", "fruity", "strong"], ["rum", "white rum", "light rum", "朗姆酒", "白朗姆"]],
  ["dark_rum", "Dark Rum", "黑朗姆酒", "spirit", "🥃", ["sweet", "smoky", "spicy", "strong"], ["dark rum", "aged rum", "黑朗姆"]],
  ["tequila", "Tequila", "龙舌兰酒", "spirit", "🌵", ["herbal", "spicy", "strong"], ["tequila", "龙舌兰", "tequila blanco"]],
  ["mezcal", "Mezcal", "梅斯卡尔", "spirit", "🌵", ["smoky", "herbal", "strong"], ["mezcal", "梅斯卡尔"]],
  ["bourbon", "Bourbon", "波本威士忌", "spirit", "🥃", ["sweet", "smoky", "spicy", "strong"], ["bourbon", "whiskey", "波本", "波本威士忌"]],
  ["rye_whiskey", "Rye Whiskey", "黑麦威士忌", "spirit", "🥃", ["dry", "spicy", "strong"], ["rye", "rye whiskey", "黑麦威士忌"]],
  ["scotch", "Scotch Whisky", "苏格兰威士忌", "spirit", "🥃", ["smoky", "dry", "strong"], ["scotch", "whisky", "苏格兰威士忌"]],
  ["cognac", "Cognac", "干邑", "spirit", "🥃", ["fruity", "spicy", "dry", "strong"], ["cognac", "干邑"]],
  ["brandy", "Brandy", "白兰地", "spirit", "🥃", ["fruity", "sweet", "strong"], ["brandy", "白兰地"]],
  ["cachaca", "Cachaça", "卡莎萨", "spirit", "🥃", ["fruity", "sweet", "strong"], ["cachaca", "卡莎萨"]],
  ["pisco", "Pisco", "皮斯科", "spirit", "🍇", ["fruity", "floral", "strong"], ["pisco", "皮斯科"]],
  ["absinthe", "Absinthe", "苦艾酒", "spirit", "🧪", ["herbal", "strong"], ["absinthe", "苦艾酒"]],
  ["aquavit", "Aquavit", "阿夸维特", "spirit", "🥃", ["herbal", "spicy", "strong"], ["aquavit", "阿夸维特"]],

  // --- Liqueurs ---
  ["triple_sec", "Triple Sec", "橙味利口酒", "liqueur", "🍊", ["sweet", "citrus"], ["triple sec", "orange liqueur", "橙味利口酒", "橙皮酒"]],
  ["cointreau", "Cointreau", "君度橙酒", "liqueur", "🍊", ["sweet", "citrus"], ["cointreau", "君度", "君度橙酒"]],
  ["curacao", "Blue Curaçao", "蓝橙酒", "liqueur", "🫐", ["sweet", "citrus", "fruity"], ["curacao", "blue curacao", "库拉索", "蓝橙酒"]],
  ["grand_marnier", "Grand Marnier", "柑曼怡", "liqueur", "🍊", ["sweet", "citrus", "spicy"], ["grand marnier", "柑曼怡"]],
  ["campari", "Campari", "金巴利", "liqueur", "🍒", ["bitter", "herbal"], ["campari", "金巴利"]],
  ["aperol", "Aperol", "阿佩罗", "liqueur", "🍊", ["bitter", "sweet", "citrus"], ["aperol", "阿佩罗"]],
  ["sweet_vermouth", "Sweet Vermouth", "甜味美思", "liqueur", "🍷", ["sweet", "herbal"], ["sweet vermouth", "rosso vermouth", "甜味美思", "红味美思"]],
  ["dry_vermouth", "Dry Vermouth", "干味美思", "liqueur", "🍸", ["dry", "herbal"], ["dry vermouth", "干味美思", "白味美思"]],
  ["lillet_blanc", "Lillet Blanc", "利莱白", "liqueur", "🍷", ["floral", "sweet", "citrus"], ["lillet", "lillet blanc", "利莱"]],
  ["maraschino", "Maraschino Liqueur", "马拉斯奇诺", "liqueur", "🍒", ["sweet", "fruity"], ["maraschino", "马拉斯奇诺"]],
  ["amaretto", "Amaretto", "杏仁利口酒", "liqueur", "🌰", ["sweet", "fruity"], ["amaretto", "阿玛雷托", "杏仁利口酒"]],
  ["coffee_liqueur", "Coffee Liqueur", "咖啡利口酒", "liqueur", "☕", ["sweet", "strong"], ["coffee liqueur", "kahlua", "咖啡利口酒"]],
  ["irish_cream", "Irish Cream", "爱尔兰奶油酒", "liqueur", "🥛", ["creamy", "sweet"], ["irish cream", "baileys", "爱尔兰奶油"]],
  ["creme_de_cacao", "Crème de Cacao", "可可利口酒", "liqueur", "🍫", ["sweet", "creamy"], ["creme de cacao", "可可利口酒"]],
  ["creme_de_violette", "Crème de Violette", "紫罗兰利口酒", "liqueur", "🟣", ["floral", "sweet"], ["creme de violette", "紫罗兰利口酒"]],
  ["benedictine", "Bénédictine", "廊酒", "liqueur", "🌿", ["herbal", "sweet", "spicy"], ["benedictine", "廊酒"]],
  ["chartreuse_green", "Green Chartreuse", "绿查特酒", "liqueur", "🟢", ["herbal", "strong", "sweet"], ["chartreuse", "green chartreuse", "绿查特", "查特酒"]],
  ["cherry_liqueur", "Cherry Liqueur", "樱桃利口酒", "liqueur", "🍒", ["sweet", "fruity"], ["cherry liqueur", "cherry heering", "樱桃利口酒"]],
  ["creme_de_menthe", "Crème de Menthe", "薄荷利口酒", "liqueur", "🌿", ["herbal", "sweet", "fresh"], ["creme de menthe", "薄荷利口酒"]],
  ["pimm_no1", "Pimm's No.1", "皮姆一号", "liqueur", "🍷", ["herbal", "fruity", "spicy"], ["pimms", "pimm's", "皮姆"]],
  ["dubonnet", "Dubonnet Rouge", "杜本内", "liqueur", "🍷", ["sweet", "herbal"], ["dubonnet", "杜本内"]],
  ["port", "Port", "波特酒", "liqueur", "🍇", ["sweet", "fruity"], ["port", "port wine", "波特"]],
  ["sherry", "Fino Sherry", "菲诺雪莉", "liqueur", "🍷", ["dry", "herbal"], ["sherry", "fino sherry", "雪莉", "雪莉酒"]],

  // --- Juices (fresh citrus also counts as its juice) ---
  ["lemon_juice", "Lemon", "柠檬", "juice", "🍋", ["sour", "citrus", "fresh"], ["lemon", "lemons", "lemon juice", "柠檬", "柠檬汁"]],
  ["lime_juice", "Lime", "青柠", "juice", "🍋", ["sour", "citrus", "fresh"], ["lime", "limes", "lime juice", "青柠", "莱姆", "青柠汁"]],
  ["orange_juice", "Orange", "橙子", "juice", "🍊", ["sweet", "fruity", "citrus"], ["orange", "orange juice", "橙子", "橙汁"]],
  ["grapefruit_juice", "Grapefruit", "西柚", "juice", "🍊", ["sour", "bitter", "citrus"], ["grapefruit", "grapefruit juice", "西柚", "葡萄柚", "葡萄柚汁"]],
  ["cranberry_juice", "Cranberry Juice", "蔓越莓汁", "juice", "🫐", ["sour", "fruity"], ["cranberry juice", "蔓越莓", "蔓越莓汁"]],
  ["pineapple_juice", "Pineapple", "菠萝", "juice", "🍍", ["sweet", "fruity"], ["pineapple", "pineapple juice", "菠萝", "凤梨", "菠萝汁"]],
  ["apple_juice", "Apple Juice", "苹果汁", "juice", "🍎", ["sweet", "fruity"], ["apple juice", "苹果汁"]],
  ["tomato_juice", "Tomato Juice", "番茄汁", "juice", "🍅", ["fresh", "sour"], ["tomato juice", "番茄汁", "西红柿汁"]],

  // --- Fresh produce ---
  ["mint", "Fresh Mint", "薄荷叶", "fresh", "🌿", ["herbal", "fresh"], ["mint", "薄荷", "薄荷叶"]],
  ["basil", "Fresh Basil", "罗勒叶", "fresh", "🌿", ["herbal", "fresh"], ["basil", "罗勒", "罗勒叶"]],
  ["cucumber", "Cucumber", "黄瓜", "fresh", "🥒", ["fresh"], ["cucumber", "黄瓜"]],
  ["berries", "Berries", "浆果", "fresh", "🫐", ["fruity", "sweet", "sour"], ["berries", "strawberry", "raspberry", "草莓", "覆盆子", "浆果"]],
  ["cherry", "Cherry", "樱桃", "fresh", "🍒", ["fruity", "sweet"], ["cherry", "樱桃"]],
  ["olive", "Olive", "橄榄", "fresh", "🫒", ["dry"], ["olive", "橄榄"]],
  ["rosemary", "Rosemary", "迷迭香", "fresh", "🌿", ["herbal"], ["rosemary", "迷迭香"]],

  // --- Sweeteners ---
  ["simple_syrup", "Simple Syrup", "糖浆", "sweetener", "🍯", ["sweet"], ["simple syrup", "sugar syrup", "syrup", "sugar", "糖", "砂糖", "白糖", "糖浆", "单糖浆", "糖水"]],
  ["honey_syrup", "Honey Syrup", "蜂蜜糖浆", "sweetener", "🍯", ["sweet", "floral"], ["honey", "honey syrup", "蜂蜜", "蜂蜜糖浆"]],
  ["agave_syrup", "Agave Syrup", "龙舌兰糖浆", "sweetener", "🍯", ["sweet"], ["agave", "agave syrup", "agave nectar", "龙舌兰糖浆"]],
  ["maple_syrup", "Maple Syrup", "枫糖浆", "sweetener", "🍁", ["sweet", "smoky"], ["maple syrup", "枫糖浆"]],
  ["grenadine", "Grenadine", "红石榴糖浆", "sweetener", "🍎", ["sweet", "fruity"], ["grenadine", "石榴糖浆", "红石榴糖浆"]],
  ["orgeat", "Orgeat Syrup", "杏仁糖浆", "sweetener", "🍯", ["sweet", "floral"], ["orgeat", "orgeat syrup", "杏仁糖浆"]],

  // --- Bitters ---
  ["angostura_bitters", "Angostura Bitters", "安格斯特拉苦精", "bitters", "🧴", ["bitter", "spicy"], ["angostura bitters", "angostura", "苦精", "安格斯特拉"]],
  ["orange_bitters", "Orange Bitters", "橙味苦精", "bitters", "🧴", ["bitter", "citrus"], ["orange bitters", "橙味苦精"]],
  ["peychauds_bitters", "Peychaud's Bitters", "佩肖苦精", "bitters", "🧴", ["bitter", "floral"], ["peychauds bitters", "peychaud's bitters", "佩肖苦精"]],

  // --- Mixers ---
  ["club_soda", "Club Soda", "苏打水", "mixer", "🫧", ["fresh"], ["club soda", "soda", "soda water", "苏打水", "气泡水"]],
  ["tonic_water", "Tonic Water", "汤力水", "mixer", "🫧", ["bitter", "fresh"], ["tonic", "tonic water", "汤力水", "汤力"]],
  ["ginger_beer", "Ginger Beer", "姜汁啤酒", "mixer", "🥤", ["spicy", "sweet", "fresh"], ["ginger beer", "姜汁啤酒"]],
  ["ginger_ale", "Ginger Ale", "姜味汽水", "mixer", "🥤", ["sweet", "spicy"], ["ginger ale", "姜味汽水"]],
  ["cola", "Cola", "可乐", "mixer", "🥤", ["sweet"], ["cola", "coke", "可乐"]],
  ["prosecco", "Prosecco", "普罗塞克起泡酒", "mixer", "🥂", ["fruity", "fresh", "sweet"], ["prosecco", "sparkling wine", "普罗塞克", "起泡酒"]],
  ["champagne", "Champagne", "香槟", "mixer", "🍾", ["dry", "fresh"], ["champagne", "香槟", "香槟酒"]],

  // --- Dairy ---
  ["cream", "Heavy Cream", "淡奶油", "dairy", "🥛", ["creamy", "sweet"], ["cream", "heavy cream", "奶油", "淡奶油"]],
  ["coconut_cream", "Coconut Cream", "椰浆", "dairy", "🥥", ["creamy", "sweet"], ["coconut cream", "椰浆", "椰子奶油"]],

  // --- Other ---
  ["egg_white", "Egg White", "蛋清", "other", "🥚", [], ["egg white", "蛋清", "蛋白"]],
  ["aquafaba", "Aquafaba", "鹰嘴豆水", "other", "🥫", [], ["aquafaba", "鹰嘴豆水"]],
  ["coffee", "Espresso", "浓缩咖啡", "other", "☕", ["strong", "bitter"], ["coffee", "espresso", "咖啡", "浓缩咖啡"]],
];

interface CocktailIngredientDef {
  id: string;
  amount: string;
  optional?: boolean;
}

interface CocktailDef {
  id: string;
  nameEn: string;
  nameZh: string;
  descEn: string;
  descZh: string;
  glass: string;
  method: string;
  difficulty: string;
  strength: string;
  flavors: string[];
  popularity: number;
  novelty: number;
  stepsEn: string[];
  stepsZh: string[];
  ingredients: CocktailIngredientDef[];
}

const COCKTAILS: CocktailDef[] = [
  {
    id: "gin_and_tonic",
    nameEn: "Gin & Tonic",
    nameZh: "金汤力",
    descEn: "The timeless, crisp highball of gin, tonic and lime.",
    descZh: "金酒与汤力水、青柠的经典清爽高球。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["bitter", "botanical", "fresh", "citrus"],
    popularity: 0.92,
    novelty: 0.18,
    stepsEn: ["Fill a highball glass with ice.", "Pour in the gin, then top with tonic water.", "Squeeze in a lime wedge and stir gently."],
    stepsZh: ["在高球杯中加满冰块。", "倒入金酒，再以汤力水补满。", "挤入青柠角并轻轻搅拌。"],
    ingredients: [
      { id: "gin", amount: "45 ml" },
      { id: "tonic_water", amount: "120 ml" },
      { id: "lime_juice", amount: "1 wedge", optional: true },
    ],
  },
  {
    id: "negroni",
    nameEn: "Negroni",
    nameZh: "尼格罗尼",
    descEn: "A bold, bittersweet Italian aperitivo of equal parts.",
    descZh: "等比例混合的浓郁意式苦甜开胃酒。",
    glass: "Old Fashioned glass",
    method: "stirred",
    difficulty: "easy",
    strength: "high",
    flavors: ["bitter", "herbal", "sweet"],
    popularity: 0.88,
    novelty: 0.28,
    stepsEn: ["Combine gin, Campari and sweet vermouth in a mixing glass with ice.", "Stir until well chilled.", "Strain into a rocks glass over a large ice cube.", "Garnish with an orange twist."],
    stepsZh: ["将金酒、金巴利和甜味美思加入加冰的调酒杯。", "搅拌至充分冷却。", "滤入放有大冰块的古典杯中。", "以橙皮装饰。"],
    ingredients: [
      { id: "gin", amount: "30 ml" },
      { id: "campari", amount: "30 ml" },
      { id: "sweet_vermouth", amount: "30 ml" },
      { id: "orange_juice", amount: "twist", optional: true },
    ],
  },
  {
    id: "dry_martini",
    nameEn: "Dry Martini",
    nameZh: "干马天尼",
    descEn: "The elegant, ice-cold essence of gin and dry vermouth.",
    descZh: "金酒与干味美思的优雅冰镇之作。",
    glass: "Coupe glass",
    method: "stirred",
    difficulty: "medium",
    strength: "high",
    flavors: ["dry", "botanical", "strong"],
    popularity: 0.9,
    novelty: 0.25,
    stepsEn: ["Chill a coupe glass.", "Stir gin and dry vermouth with ice until very cold.", "Strain into the chilled glass.", "Express a lemon peel over the top and drop it in."],
    stepsZh: ["冰镇一个鸡尾酒杯。", "将金酒和干味美思加冰搅拌至极冷。", "滤入冰镇杯中。", "拧出柠檬皮油并投入杯中。"],
    ingredients: [
      { id: "gin", amount: "60 ml" },
      { id: "dry_vermouth", amount: "10 ml" },
      { id: "lemon_juice", amount: "twist", optional: true },
    ],
  },
  {
    id: "gimlet",
    nameEn: "Gimlet",
    nameZh: "吉姆雷特",
    descEn: "A clean, tart gin sour sweetened just enough.",
    descZh: "酸甜平衡、干净利落的金酒酸酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "citrus", "sweet"],
    popularity: 0.72,
    novelty: 0.3,
    stepsEn: ["Shake gin, lime and simple syrup with ice.", "Double-strain into a chilled coupe.", "Garnish with a lime wheel."],
    stepsZh: ["将金酒、青柠和糖浆加冰摇匀。", "双重过滤至冰镇杯中。", "以青柠片装饰。"],
    ingredients: [
      { id: "gin", amount: "60 ml" },
      { id: "lime_juice", amount: "20 ml" },
      { id: "simple_syrup", amount: "15 ml" },
    ],
  },
  {
    id: "tom_collins",
    nameEn: "Tom Collins",
    nameZh: "汤姆柯林斯",
    descEn: "A tall, sparkling gin lemonade — refreshing to the last sip.",
    descZh: "满满气泡的金酒柠檬汽水，清爽到底。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["fresh", "citrus", "sour"],
    popularity: 0.8,
    novelty: 0.22,
    stepsEn: ["Shake gin, lemon and simple syrup with ice.", "Strain into an ice-filled highball glass.", "Top with soda water and garnish with a lemon wheel."],
    stepsZh: ["将金酒、柠檬和糖浆加冰摇匀。", "滤入加冰的高球杯。", "倒入苏打水补满，以柠檬片装饰。"],
    ingredients: [
      { id: "gin", amount: "45 ml" },
      { id: "lemon_juice", amount: "25 ml" },
      { id: "simple_syrup", amount: "15 ml" },
      { id: "club_soda", amount: "to top" },
    ],
  },
  {
    id: "gin_fizz",
    nameEn: "Gin Fizz",
    nameZh: "金菲士",
    descEn: "A bright, frothy gin sour — add soda for extra sparkle.",
    descZh: "明亮带泡的金酒酸酒，加苏打更清爽。",
    glass: "Highball glass",
    method: "shaken",
    difficulty: "medium",
    strength: "medium",
    flavors: ["fresh", "citrus", "sour"],
    popularity: 0.75,
    novelty: 0.26,
    stepsEn: ["Dry-shake gin, lemon, syrup and egg white (if using).", "Shake again with ice.", "Strain into an ice-filled glass and top with soda water."],
    stepsZh: ["将金酒、柠檬、糖浆（和蛋清）先干摇。", "加冰再摇一次。", "滤入加冰杯中，倒入苏打水补满。"],
    ingredients: [
      { id: "gin", amount: "45 ml" },
      { id: "lemon_juice", amount: "25 ml" },
      { id: "simple_syrup", amount: "15 ml" },
      { id: "egg_white", amount: "15 ml", optional: true },
      { id: "club_soda", amount: "to top", optional: true },
    ],
  },
  {
    id: "french_75",
    nameEn: "French 75",
    nameZh: "法式75",
    descEn: "Champagne lifts a lemon-gin sour into elegant celebration.",
    descZh: "香槟让金酒柠檬酸酒升华为优雅的庆祝。",
    glass: "Champagne flute",
    method: "shaken",
    difficulty: "medium",
    strength: "high",
    flavors: ["citrus", "fresh", "fruity"],
    popularity: 0.82,
    novelty: 0.32,
    stepsEn: ["Shake gin, lemon and simple syrup with ice.", "Strain into a chilled flute.", "Top with chilled champagne and garnish with a lemon twist."],
    stepsZh: ["将金酒、柠檬和糖浆加冰摇匀。", "滤入冰镇香槟杯。", "倒入冰镇香槟补满，以柠檬皮装饰。"],
    ingredients: [
      { id: "gin", amount: "30 ml" },
      { id: "lemon_juice", amount: "15 ml" },
      { id: "simple_syrup", amount: "10 ml" },
      { id: "champagne", amount: "to top" },
    ],
  },
  {
    id: "bees_knees",
    nameEn: "Bee's Knees",
    nameZh: "蜂之膝",
    descEn: "Honey, lemon and gin — the prohibition-era classic.",
    descZh: "蜂蜜、柠檬与金酒的禁酒令时期经典。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "sweet", "floral", "citrus"],
    popularity: 0.66,
    novelty: 0.4,
    stepsEn: ["Shake gin, lemon and honey syrup hard with ice.", "Double-strain into a chilled coupe.", "Garnish with a lemon twist."],
    stepsZh: ["将金酒、柠檬和蜂蜜糖浆加冰用力摇匀。", "双重过滤至冰镇杯中。", "以柠檬皮装饰。"],
    ingredients: [
      { id: "gin", amount: "50 ml" },
      { id: "lemon_juice", amount: "20 ml" },
      { id: "honey_syrup", amount: "15 ml" },
    ],
  },
  {
    id: "aviation",
    nameEn: "Aviation",
    nameZh: "飞行者",
    descEn: "A pale violet, floral gin sour with maraschino depth.",
    descZh: "淡紫色、花香四溢的马拉斯奇诺金酒酸酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "medium",
    strength: "medium",
    flavors: ["floral", "sour", "citrus"],
    popularity: 0.68,
    novelty: 0.48,
    stepsEn: ["Shake gin, lemon, maraschino and crème de violette with ice.", "Strain into a chilled coupe.", "Garnish with a cherry."],
    stepsZh: ["将金酒、柠檬、马拉斯奇诺和紫罗兰利口酒加冰摇匀。", "滤入冰镇杯中。", "以樱桃装饰。"],
    ingredients: [
      { id: "gin", amount: "45 ml" },
      { id: "lemon_juice", amount: "15 ml" },
      { id: "maraschino", amount: "10 ml" },
      { id: "creme_de_violette", amount: "7.5 ml", optional: true },
    ],
  },
  {
    id: "last_word",
    nameEn: "Last Word",
    nameZh: "临别一言",
    descEn: "Equal parts gin, chartreuse, maraschino and lime — sharp and herbal.",
    descZh: "金酒、查特、马拉斯奇诺与青柠等量调和，锐利草本。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "medium",
    strength: "high",
    flavors: ["sour", "herbal", "citrus"],
    popularity: 0.64,
    novelty: 0.52,
    stepsEn: ["Add all four ingredients to a shaker with ice.", "Shake hard and double-strain into a coupe."],
    stepsZh: ["将四种材料加入加冰摇壶。", "用力摇匀后双重过滤入杯。"],
    ingredients: [
      { id: "gin", amount: "22.5 ml" },
      { id: "chartreuse_green", amount: "22.5 ml" },
      { id: "maraschino", amount: "22.5 ml" },
      { id: "lime_juice", amount: "22.5 ml" },
    ],
  },
  {
    id: "southside",
    nameEn: "Southside",
    nameZh: "南区酸酒",
    descEn: "A minty gin sour — the gangster's gimlet.",
    descZh: "薄荷香气的金酒酸酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["fresh", "herbal", "sour"],
    popularity: 0.58,
    novelty: 0.5,
    stepsEn: ["Gently shake gin, lemon, syrup and mint with ice.", "Double-strain into a coupe.", "Slap a mint leaf and garnish."],
    stepsZh: ["将金酒、柠檬、糖浆和薄荷加冰轻摇。", "双重过滤入杯。", "轻拍一片薄荷叶装饰。"],
    ingredients: [
      { id: "gin", amount: "50 ml" },
      { id: "lemon_juice", amount: "25 ml" },
      { id: "simple_syrup", amount: "15 ml" },
      { id: "mint", amount: "6 leaves", optional: true },
    ],
  },
  // --- Vodka ---
  {
    id: "cosmopolitan",
    nameEn: "Cosmopolitan",
    nameZh: "大都会",
    descEn: "A tart, cranberry-pink modern classic.",
    descZh: "酸甜蔓越莓色的现代经典。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "citrus", "fruity"],
    popularity: 0.85,
    novelty: 0.28,
    stepsEn: ["Shake vodka, triple sec, lime and cranberry with ice.", "Strain into a chilled coupe.", "Garnish with an orange twist."],
    stepsZh: ["将伏特加、橙味利口酒、青柠和蔓越莓汁加冰摇匀。", "滤入冰镇杯中。", "以橙皮装饰。"],
    ingredients: [
      { id: "vodka", amount: "40 ml" },
      { id: "triple_sec", amount: "15 ml" },
      { id: "lime_juice", amount: "15 ml" },
      { id: "cranberry_juice", amount: "30 ml" },
    ],
  },
  {
    id: "vodka_martini",
    nameEn: "Vodka Martini",
    nameZh: "伏特加马天尼",
    descEn: "Ice-cold vodka, barely touched by dry vermouth.",
    descZh: "几乎只有伏特加的极冷马天尼。",
    glass: "Coupe glass",
    method: "stirred",
    difficulty: "medium",
    strength: "high",
    flavors: ["dry", "strong"],
    popularity: 0.82,
    novelty: 0.22,
    stepsEn: ["Stir vodka and dry vermouth with ice until very cold.", "Strain into a chilled coupe.", "Garnish with an olive or lemon twist."],
    stepsZh: ["将伏特加和干味美思加冰搅拌至极冷。", "滤入冰镇杯中。", "以橄榄或柠檬皮装饰。"],
    ingredients: [
      { id: "vodka", amount: "60 ml" },
      { id: "dry_vermouth", amount: "10 ml" },
      { id: "olive", amount: "1", optional: true },
    ],
  },
  {
    id: "moscow_mule",
    nameEn: "Moscow Mule",
    nameZh: "莫斯科骡子",
    descEn: "Vodka, lime and ginger beer in a frosty copper mug.",
    descZh: "伏特加、青柠与姜汁啤酒的铜杯特调。",
    glass: "Copper mug",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["spicy", "fresh", "sour"],
    popularity: 0.86,
    novelty: 0.24,
    stepsEn: ["Fill a copper mug with ice.", "Add vodka and lime juice.", "Top with ginger beer and stir."],
    stepsZh: ["在铜杯中加入冰块。", "倒入伏特加和青柠汁。", "以姜汁啤酒补满并搅拌。"],
    ingredients: [
      { id: "vodka", amount: "45 ml" },
      { id: "lime_juice", amount: "15 ml" },
      { id: "ginger_beer", amount: "120 ml" },
    ],
  },
  {
    id: "espresso_martini",
    nameEn: "Espresso Martini",
    nameZh: "浓缩咖啡马天尼",
    descEn: "Vodka, coffee and a creamy foam — the after-dinner pick-me-up.",
    descZh: "伏特加、咖啡与细腻泡沫的餐后提神酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "medium",
    strength: "medium",
    flavors: ["strong", "bitter", "sweet"],
    popularity: 0.84,
    novelty: 0.34,
    stepsEn: ["Shake vodka, coffee liqueur, espresso and syrup hard with ice.", "Double-strain into a coupe.", "Garnish with three coffee beans."],
    stepsZh: ["将伏特加、咖啡利口酒、浓缩咖啡和糖浆加冰用力摇匀。", "双重过滤入杯。", "以三颗咖啡豆装饰。"],
    ingredients: [
      { id: "vodka", amount: "40 ml" },
      { id: "coffee_liqueur", amount: "20 ml" },
      { id: "coffee", amount: "30 ml" },
      { id: "simple_syrup", amount: "10 ml", optional: true },
    ],
  },
  {
    id: "bloody_mary",
    nameEn: "Bloody Mary",
    nameZh: "血腥玛丽",
    descEn: "A savoury, spiced tomato-vodka brunch staple.",
    descZh: "咸香辛口的番茄伏特加早午餐经典。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["fresh", "sour", "spicy"],
    popularity: 0.72,
    novelty: 0.38,
    stepsEn: ["Add vodka, tomato juice, lemon and a dash of bitters to an ice-filled glass.", "Season to taste and stir.", "Garnish with a celery stick or lemon."],
    stepsZh: ["在加冰的杯中倒入伏特加、番茄汁、柠檬和少许苦精。", "按口味调味并搅拌。", "以芹菜杆或柠檬装饰。"],
    ingredients: [
      { id: "vodka", amount: "45 ml" },
      { id: "tomato_juice", amount: "120 ml" },
      { id: "lemon_juice", amount: "15 ml" },
      { id: "angostura_bitters", amount: "2 dashes", optional: true },
    ],
  },
  {
    id: "white_russian",
    nameEn: "White Russian",
    nameZh: "白俄罗斯",
    descEn: "Vodka, coffee liqueur and cream — dessert in a glass.",
    descZh: "伏特加、咖啡利口酒与奶油的杯装甜点。",
    glass: "Old Fashioned glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["creamy", "sweet", "strong"],
    popularity: 0.74,
    novelty: 0.32,
    stepsEn: ["Fill a rocks glass with ice.", "Pour vodka and coffee liqueur.", "Float heavy cream on top and stir gently."],
    stepsZh: ["在古典杯中加冰。", "倒入伏特加和咖啡利口酒。", "轻轻倒入淡奶油并搅拌。"],
    ingredients: [
      { id: "vodka", amount: "45 ml" },
      { id: "coffee_liqueur", amount: "20 ml" },
      { id: "cream", amount: "30 ml" },
    ],
  },
  // --- Rum ---
  {
    id: "mojito",
    nameEn: "Mojito",
    nameZh: "莫吉托",
    descEn: "Mint, lime and rum over crushed ice — pure summer.",
    descZh: "薄荷、青柠与朗姆酒的碎冰夏日特调。",
    glass: "Highball glass",
    method: "muddled",
    difficulty: "easy",
    strength: "medium",
    flavors: ["fresh", "herbal", "sour", "sweet"],
    popularity: 0.9,
    novelty: 0.2,
    stepsEn: ["Muddle mint, lime and simple syrup gently in a glass.", "Add white rum and fill with crushed ice.", "Top with soda water and stir."],
    stepsZh: ["在杯中轻轻捣压薄荷、青柠和糖浆。", "加入白朗姆酒并填满碎冰。", "倒入苏打水补满并搅拌。"],
    ingredients: [
      { id: "white_rum", amount: "45 ml" },
      { id: "lime_juice", amount: "20 ml" },
      { id: "simple_syrup", amount: "15 ml" },
      { id: "mint", amount: "8 leaves" },
      { id: "club_soda", amount: "to top" },
    ],
  },
  {
    id: "daiquiri",
    nameEn: "Daiquiri",
    nameZh: "得其利",
    descEn: "Rum, lime and sugar — the perfect three-ingredient sour.",
    descZh: "朗姆、青柠与糖的三料经典酸酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "sweet", "citrus"],
    popularity: 0.86,
    novelty: 0.22,
    stepsEn: ["Shake white rum, lime and simple syrup with ice.", "Double-strain into a chilled coupe.", "Garnish with a lime wheel."],
    stepsZh: ["将白朗姆、青柠和糖浆加冰摇匀。", "双重过滤至冰镇杯中。", "以青柠片装饰。"],
    ingredients: [
      { id: "white_rum", amount: "50 ml" },
      { id: "lime_juice", amount: "25 ml" },
      { id: "simple_syrup", amount: "15 ml" },
    ],
  },
  {
    id: "pina_colada",
    nameEn: "Piña Colada",
    nameZh: "椰林飘香",
    descEn: "Rum, coconut and pineapple blended into a tropical shake.",
    descZh: "朗姆、椰浆与菠萝打成的热带奶昔。",
    glass: "Hurricane glass",
    method: "blended",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sweet", "creamy", "fruity"],
    popularity: 0.82,
    novelty: 0.3,
    stepsEn: ["Blend rum, coconut cream and pineapple juice with ice.", "Pour into a hurricane glass.", "Garnish with a pineapple wedge."],
    stepsZh: ["将朗姆、椰浆和菠萝汁加冰搅打。", "倒入飓风杯。", "以菠萝片装饰。"],
    ingredients: [
      { id: "white_rum", amount: "45 ml" },
      { id: "coconut_cream", amount: "30 ml" },
      { id: "pineapple_juice", amount: "60 ml" },
    ],
  },
  {
    id: "mai_tai",
    nameEn: "Mai Tai",
    nameZh: "迈泰",
    descEn: "A layered tiki classic with rum, citrus, curaçao and orgeat.",
    descZh: "朗姆、柑橘、库拉索与杏仁糖浆交织的提基经典。",
    glass: "Old Fashioned glass",
    method: "shaken",
    difficulty: "medium",
    strength: "high",
    flavors: ["sweet", "fruity", "citrus"],
    popularity: 0.78,
    novelty: 0.4,
    stepsEn: ["Shake rums, lime, curaçao, orgeat and syrup with ice.", "Strain into a rocks glass over crushed ice.", "Garnish with mint and a lime wheel."],
    stepsZh: ["将两种朗姆、青柠、库拉索、杏仁糖浆和糖浆加冰摇匀。", "滤入盛碎冰的古典杯。", "以薄荷和青柠片装饰。"],
    ingredients: [
      { id: "white_rum", amount: "30 ml" },
      { id: "dark_rum", amount: "15 ml" },
      { id: "lime_juice", amount: "20 ml" },
      { id: "curacao", amount: "15 ml" },
      { id: "orgeat", amount: "15 ml" },
      { id: "simple_syrup", amount: "5 ml", optional: true },
    ],
  },
  {
    id: "dark_and_stormy",
    nameEn: "Dark 'n' Stormy",
    nameZh: "黑暗风暴",
    descEn: "Dark rum and fiery ginger beer — bold and simple.",
    descZh: "黑朗姆与辛辣姜汁啤酒的大胆组合。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["spicy", "sweet", "fresh"],
    popularity: 0.76,
    novelty: 0.3,
    stepsEn: ["Fill a highball glass with ice.", "Pour in the dark rum.", "Top with ginger beer and a lime wedge."],
    stepsZh: ["在高球杯中加冰。", "倒入黑朗姆。", "以姜汁啤酒补满并加青柠角。"],
    ingredients: [
      { id: "dark_rum", amount: "50 ml" },
      { id: "ginger_beer", amount: "120 ml" },
      { id: "lime_juice", amount: "wedge", optional: true },
    ],
  },
  {
    id: "cuba_libre",
    nameEn: "Cuba Libre",
    nameZh: "自由古巴",
    descEn: "Rum, cola and lime — the easy crowd-pleaser.",
    descZh: "朗姆、可乐与青柠的人气特调。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sweet", "fresh", "citrus"],
    popularity: 0.8,
    novelty: 0.2,
    stepsEn: ["Fill a highball glass with ice.", "Add rum and squeeze in a lime wedge.", "Top with cola."],
    stepsZh: ["在高球杯中加冰。", "加入朗姆并挤入青柠角。", "以可乐补满。"],
    ingredients: [
      { id: "white_rum", amount: "45 ml" },
      { id: "cola", amount: "120 ml" },
      { id: "lime_juice", amount: "wedge" },
    ],
  },
  {
    id: "caipirinha",
    nameEn: "Caipirinha",
    nameZh: "凯匹林纳",
    descEn: "Brazil's national drink — cachaça, lime and sugar.",
    descZh: "巴西国民鸡尾酒：卡莎萨、青柠与糖。",
    glass: "Old Fashioned glass",
    method: "muddled",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "sweet", "citrus"],
    popularity: 0.7,
    novelty: 0.36,
    stepsEn: ["Muddle lime and simple syrup in a rocks glass.", "Fill with ice and pour in cachaça.", "Stir well."],
    stepsZh: ["在古典杯中捣压青柠和糖浆。", "加冰并倒入卡莎萨。", "搅拌均匀。"],
    ingredients: [
      { id: "cachaca", amount: "50 ml" },
      { id: "lime_juice", amount: "20 ml" },
      { id: "simple_syrup", amount: "10 ml" },
    ],
  },
  // --- Tequila ---
  {
    id: "margarita",
    nameEn: "Margarita",
    nameZh: "玛格丽特",
    descEn: "Tequila, triple sec and lime with a salted rim.",
    descZh: "龙舌兰、橙味利口酒与青柠的盐边经典。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "citrus", "sweet"],
    popularity: 0.9,
    novelty: 0.2,
    stepsEn: ["Rim a glass with salt.", "Shake tequila, triple sec and lime with ice.", "Strain into the rimmed glass over fresh ice."],
    stepsZh: ["杯口沾盐。", "将龙舌兰、橙味利口酒和青柠加冰摇匀。", "滤入带盐边的加冰杯中。"],
    ingredients: [
      { id: "tequila", amount: "45 ml" },
      { id: "triple_sec", amount: "20 ml" },
      { id: "lime_juice", amount: "20 ml" },
    ],
  },
  {
    id: "paloma",
    nameEn: "Paloma",
    nameZh: "帕洛玛",
    descEn: "Tequila and grapefruit soda — bracingly refreshing.",
    descZh: "龙舌兰与西柚汽水，清爽宜人。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["bitter", "fresh", "citrus"],
    popularity: 0.76,
    novelty: 0.28,
    stepsEn: ["Fill a highball glass with ice.", "Add tequila, grapefruit and lime.", "Top with soda water and stir."],
    stepsZh: ["在高球杯中加冰。", "加入龙舌兰、西柚和青柠。", "倒入苏打水补满并搅拌。"],
    ingredients: [
      { id: "tequila", amount: "45 ml" },
      { id: "grapefruit_juice", amount: "60 ml" },
      { id: "lime_juice", amount: "10 ml" },
      { id: "club_soda", amount: "to top" },
    ],
  },
  {
    id: "tequila_sunrise",
    nameEn: "Tequila Sunrise",
    nameZh: "龙舌兰日出",
    descEn: "Orange juice and grenadine create a sunrise in a glass.",
    descZh: "橙汁与石榴糖浆在杯中晕出日出。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sweet", "fruity", "citrus"],
    popularity: 0.74,
    novelty: 0.3,
    stepsEn: ["Fill a glass with ice and pour tequila and orange juice.", "Slowly pour grenadine so it sinks.", "Do not stir; garnish with an orange slice."],
    stepsZh: ["杯中加冰，倒入龙舌兰和橙汁。", "缓缓倒入石榴糖浆使其下沉。", "不要搅拌，以橙片装饰。"],
    ingredients: [
      { id: "tequila", amount: "45 ml" },
      { id: "orange_juice", amount: "120 ml" },
      { id: "grenadine", amount: "10 ml" },
    ],
  },
  {
    id: "tommys_margarita",
    nameEn: "Tommy's Margarita",
    nameZh: "汤米玛格丽特",
    descEn: "A cleaner margarita sweetened with agave instead of liqueur.",
    descZh: "以龙舌兰糖浆代替利口酒的清爽玛格丽特。",
    glass: "Old Fashioned glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "citrus", "sweet"],
    popularity: 0.68,
    novelty: 0.42,
    stepsEn: ["Shake tequila, lime and agave syrup with ice.", "Strain into a rocks glass over ice."],
    stepsZh: ["将龙舌兰、青柠和龙舌兰糖浆加冰摇匀。", "滤入加冰的古典杯。"],
    ingredients: [
      { id: "tequila", amount: "50 ml" },
      { id: "lime_juice", amount: "20 ml" },
      { id: "agave_syrup", amount: "15 ml" },
    ],
  },
  // --- Whiskey ---
  {
    id: "old_fashioned",
    nameEn: "Old Fashioned",
    nameZh: "古典",
    descEn: "Whiskey, sugar and bitters — the original cocktail.",
    descZh: "威士忌、糖与苦精的最初鸡尾酒。",
    glass: "Old Fashioned glass",
    method: "stirred",
    difficulty: "easy",
    strength: "high",
    flavors: ["strong", "bitter", "sweet", "smoky"],
    popularity: 0.95,
    novelty: 0.16,
    stepsEn: ["Stir sugar, bitters and a splash of water in a rocks glass.", "Add bourbon and a large ice cube.", "Stir and garnish with an orange twist."],
    stepsZh: ["在古典杯中搅拌糖、苦精和少许水。", "加入波本和一大块冰。", "搅拌并以橙皮装饰。"],
    ingredients: [
      { id: "bourbon", amount: "60 ml" },
      { id: "simple_syrup", amount: "5 ml" },
      { id: "angostura_bitters", amount: "2 dashes" },
      { id: "orange_juice", amount: "twist", optional: true },
    ],
  },
  {
    id: "manhattan",
    nameEn: "Manhattan",
    nameZh: "曼哈顿",
    descEn: "Rye and sweet vermouth with a whisper of bitters.",
    descZh: "黑麦威士忌与甜味美思加少许苦精。",
    glass: "Coupe glass",
    method: "stirred",
    difficulty: "medium",
    strength: "high",
    flavors: ["herbal", "sweet", "strong"],
    popularity: 0.88,
    novelty: 0.22,
    stepsEn: ["Stir rye, sweet vermouth and bitters with ice.", "Strain into a chilled coupe.", "Garnish with a cherry."],
    stepsZh: ["将黑麦威士忌、甜味美思和苦精加冰搅拌。", "滤入冰镇杯中。", "以樱桃装饰。"],
    ingredients: [
      { id: "rye_whiskey", amount: "50 ml" },
      { id: "sweet_vermouth", amount: "25 ml" },
      { id: "angostura_bitters", amount: "2 dashes" },
      { id: "cherry", amount: "1", optional: true },
    ],
  },
  {
    id: "whiskey_sour",
    nameEn: "Whiskey Sour",
    nameZh: "威士忌酸酒",
    descEn: "Bourbon, lemon and sugar with a silky foam.",
    descZh: "波本、柠檬与糖的丝滑酸酒。",
    glass: "Old Fashioned glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["sour", "sweet", "strong"],
    popularity: 0.86,
    novelty: 0.22,
    stepsEn: ["Dry-shake whiskey, lemon, syrup and egg white (if using).", "Shake again with ice.", "Strain over ice and garnish with a cherry."],
    stepsZh: ["将威士忌、柠檬、糖浆（和蛋清）先干摇。", "加冰再摇一次。", "滤入加冰杯中，以樱桃装饰。"],
    ingredients: [
      { id: "bourbon", amount: "50 ml" },
      { id: "lemon_juice", amount: "25 ml" },
      { id: "simple_syrup", amount: "15 ml" },
      { id: "egg_white", amount: "15 ml", optional: true },
    ],
  },
  {
    id: "boulevardier",
    nameEn: "Boulevardier",
    nameZh: "大道",
    descEn: "The Negroni's whiskey cousin — bitter, warm and rich.",
    descZh: "尼格罗尼的威士忌兄弟：苦、暖、醇。",
    glass: "Coupe glass",
    method: "stirred",
    difficulty: "easy",
    strength: "high",
    flavors: ["bitter", "herbal", "sweet"],
    popularity: 0.66,
    novelty: 0.44,
    stepsEn: ["Stir bourbon, Campari and sweet vermouth with ice.", "Strain into a rocks glass over a large cube.", "Garnish with an orange twist."],
    stepsZh: ["将波本、金巴利和甜味美思加冰搅拌。", "滤入放大冰块的古典杯。", "以橙皮装饰。"],
    ingredients: [
      { id: "bourbon", amount: "45 ml" },
      { id: "campari", amount: "30 ml" },
      { id: "sweet_vermouth", amount: "30 ml" },
    ],
  },
  {
    id: "sazerac",
    nameEn: "Sazerac",
    nameZh: "萨兹洛克",
    descEn: "New Orleans' rye classic with an absinthe rinse.",
    descZh: "新奥尔良黑麦经典，带苦艾润杯。",
    glass: "Old Fashioned glass",
    method: "stirred",
    difficulty: "advanced",
    strength: "high",
    flavors: ["strong", "bitter", "herbal"],
    popularity: 0.7,
    novelty: 0.42,
    stepsEn: ["Rinse a chilled glass with absinthe and discard the excess.", "Stir rye, syrup and Peychaud's with ice.", "Strain into the rinsed glass and garnish with a lemon twist."],
    stepsZh: ["用苦艾酒润洗冰镇杯并倒掉多余。", "将黑麦、糖浆和佩肖苦精加冰搅拌。", "滤入润洗杯中，以柠檬皮装饰。"],
    ingredients: [
      { id: "rye_whiskey", amount: "50 ml" },
      { id: "simple_syrup", amount: "10 ml" },
      { id: "peychauds_bitters", amount: "2 dashes" },
      { id: "absinthe", amount: "2 ml" },
    ],
  },
  // --- Brandy ---
  {
    id: "sidecar",
    nameEn: "Sidecar",
    nameZh: "边车",
    descEn: "Cognac, orange liqueur and lemon — a refined sour.",
    descZh: "干邑、橙味利口酒与柠檬的优雅酸酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "medium",
    strength: "medium",
    flavors: ["sour", "citrus", "sweet"],
    popularity: 0.76,
    novelty: 0.32,
    stepsEn: ["Shake cognac, triple sec and lemon with ice.", "Strain into a sugar-rimmed coupe.", "Garnish with an orange twist."],
    stepsZh: ["将干邑、橙味利口酒和柠檬加冰摇匀。", "滤入带糖边的杯中。", "以橙皮装饰。"],
    ingredients: [
      { id: "cognac", amount: "45 ml" },
      { id: "triple_sec", amount: "20 ml" },
      { id: "lemon_juice", amount: "20 ml" },
    ],
  },
  {
    id: "brandy_alexander",
    nameEn: "Brandy Alexander",
    nameZh: "白兰地亚历山大",
    descEn: "Brandy, cacao and cream — a silky dessert cocktail.",
    descZh: "白兰地、可可与奶油的丝滑甜点酒。",
    glass: "Coupe glass",
    method: "shaken",
    difficulty: "easy",
    strength: "medium",
    flavors: ["creamy", "sweet", "strong"],
    popularity: 0.6,
    novelty: 0.36,
    stepsEn: ["Shake brandy, crème de cacao and cream with ice.", "Strain into a chilled coupe.", "Grate nutmeg on top."],
    stepsZh: ["将白兰地、可可利口酒和奶油加冰摇匀。", "滤入冰镇杯中。", "表面擦少许肉豆蔻。"],
    ingredients: [
      { id: "brandy", amount: "30 ml" },
      { id: "creme_de_cacao", amount: "30 ml" },
      { id: "cream", amount: "30 ml" },
    ],
  },
  // --- Aperitifs & Sparkling ---
  {
    id: "aperol_spritz",
    nameEn: "Aperol Spritz",
    nameZh: "阿佩罗气泡",
    descEn: "Aperol, prosecco and soda — the sunny Italian spritz.",
    descZh: "阿佩罗、普罗塞克与苏打的意式气泡。",
    glass: "Wine glass",
    method: "built",
    difficulty: "easy",
    strength: "low",
    flavors: ["bitter", "fresh", "citrus", "sweet"],
    popularity: 0.88,
    novelty: 0.26,
    stepsEn: ["Fill a wine glass with ice.", "Pour Aperol, then prosecco.", "Add a splash of soda and an orange slice."],
    stepsZh: ["在葡萄酒杯中加冰。", "倒入阿佩罗，再加入普罗塞克。", "加少许苏打并以橙片装饰。"],
    ingredients: [
      { id: "aperol", amount: "60 ml" },
      { id: "prosecco", amount: "90 ml" },
      { id: "club_soda", amount: "splash" },
      { id: "orange_juice", amount: "slice", optional: true },
    ],
  },
  {
    id: "americano",
    nameEn: "Americano",
    nameZh: "美国佬",
    descEn: "Campari and sweet vermouth lengthened with soda.",
    descZh: "金巴利与甜味美思加苏打稀释。",
    glass: "Highball glass",
    method: "built",
    difficulty: "easy",
    strength: "low",
    flavors: ["bitter", "herbal", "sweet"],
    popularity: 0.62,
    novelty: 0.4,
    stepsEn: ["Fill a highball glass with ice.", "Add Campari and sweet vermouth.", "Top with soda water and garnish with orange."],
    stepsZh: ["在高球杯中加冰。", "加入金巴利和甜味美思。", "以苏打水补满，橙片装饰。"],
    ingredients: [
      { id: "campari", amount: "30 ml" },
      { id: "sweet_vermouth", amount: "30 ml" },
      { id: "club_soda", amount: "60 ml" },
    ],
  },
  {
    id: "mimosa",
    nameEn: "Mimosa",
    nameZh: "含羞草",
    descEn: "Champagne and fresh orange juice — brunch in a flute.",
    descZh: "香槟与鲜橙汁的早午餐香槟杯。",
    glass: "Champagne flute",
    method: "built",
    difficulty: "easy",
    strength: "low",
    flavors: ["sweet", "fruity", "citrus"],
    popularity: 0.7,
    novelty: 0.2,
    stepsEn: ["Half-fill a flute with chilled orange juice.", "Top slowly with chilled champagne."],
    stepsZh: ["在香槟杯中倒入半杯冰镇橙汁。", "缓缓倒入冰镇香槟补满。"],
    ingredients: [
      { id: "champagne", amount: "90 ml" },
      { id: "orange_juice", amount: "90 ml" },
    ],
  },
];

// Real cocktail photography from TheCocktailDB (public, free API).
// Cocktails absent from TheCocktailDB (e.g. Southside) keep the styled emoji placeholder.
const IMAGE_URLS: Record<string, string> = {
  gin_and_tonic: "https://www.thecocktaildb.com/images/media/drink/k0508k1668422436.jpg",
  negroni: "https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg",
  dry_martini: "https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg",
  gimlet: "https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg",
  tom_collins: "https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg",
  gin_fizz: "https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg",
  french_75: "https://www.thecocktaildb.com/images/media/drink/hrxfbl1606773109.jpg",
  bees_knees: "https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg",
  // Southside doesn't exist on TheCocktailDB; use a visually-identical
  // gin + herb + citrus photo (Gin Basil Smash) rather than a placeholder.
  southside: "https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg",
  aviation: "https://www.thecocktaildb.com/images/media/drink/trbplb1606855233.jpg",
  last_word: "https://www.thecocktaildb.com/images/media/drink/91oule1513702624.jpg",
  cosmopolitan: "https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg",
  vodka_martini: "https://www.thecocktaildb.com/images/media/drink/qyxrqw1439906528.jpg",
  moscow_mule: "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg",
  espresso_martini: "https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg",
  bloody_mary: "https://www.thecocktaildb.com/images/media/drink/t6caa21582485702.jpg",
  white_russian: "https://www.thecocktaildb.com/images/media/drink/vsrupw1472405732.jpg",
  mojito: "https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg",
  daiquiri: "https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg",
  pina_colada: "https://www.thecocktaildb.com/images/media/drink/upgsue1668419912.jpg",
  mai_tai: "https://www.thecocktaildb.com/images/media/drink/twyrrp1439907470.jpg",
  dark_and_stormy: "https://www.thecocktaildb.com/images/media/drink/t1tn0s1504374905.jpg",
  cuba_libre: "https://www.thecocktaildb.com/images/media/drink/wmkbfj1606853905.jpg",
  caipirinha: "https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg",
  margarita: "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
  paloma: "https://www.thecocktaildb.com/images/media/drink/samm5j1513706393.jpg",
  tequila_sunrise: "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
  tommys_margarita: "https://www.thecocktaildb.com/images/media/drink/loezxn1504373874.jpg",
  old_fashioned: "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
  manhattan: "https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg",
  whiskey_sour: "https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg",
  boulevardier: "https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg",
  sazerac: "https://www.thecocktaildb.com/images/media/drink/vvpxwy1439907208.jpg",
  sidecar: "https://www.thecocktaildb.com/images/media/drink/x72sik1606854964.jpg",
  brandy_alexander: "https://www.thecocktaildb.com/images/media/drink/mlyk1i1606772340.jpg",
  aperol_spritz: "https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg",
  americano: "https://www.thecocktaildb.com/images/media/drink/709s6m1613655124.jpg",
  mimosa: "https://www.thecocktaildb.com/images/media/drink/juhcuu1504370685.jpg",
};

async function main() {
  console.log("Clearing existing data…");
  await prisma.cocktailIngredient.deleteMany();
  await prisma.ingredientAlias.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.userInventory.deleteMany();
  await prisma.cocktail.deleteMany();
  await prisma.ingredient.deleteMany();

  console.log(`Seeding ${INGREDIENTS.length} ingredients…`);
  const usedAliases = new Set<string>();
  for (const [id, nameEn, nameZh, category, emoji, flavors, aliases] of INGREDIENTS) {
    await prisma.ingredient.create({
      data: {
        id,
        nameEn,
        nameZh,
        category,
        emoji,
        flavorProfile: JSON.stringify(flavors),
        aliases: {
          create: aliases
            .filter((a) => {
              const key = a.toLowerCase();
              if (usedAliases.has(key)) return false;
              usedAliases.add(key);
              return true;
            })
            .map((alias) => ({ alias, language: "any" })),
        },
      },
    });
  }

  console.log(`Seeding ${COCKTAILS.length} cocktails…`);
  for (const c of COCKTAILS) {
    await prisma.cocktail.create({
      data: {
        id: c.id,
        nameEn: c.nameEn,
        nameZh: c.nameZh,
        descriptionEn: c.descEn,
        descriptionZh: c.descZh,
        glass: c.glass,
        method: c.method,
        difficulty: c.difficulty,
        strength: c.strength,
        flavorProfile: JSON.stringify(c.flavors),
        stepsEn: JSON.stringify(c.stepsEn),
        stepsZh: JSON.stringify(c.stepsZh),
        popularity: c.popularity,
        novelty: c.novelty,
        source: "classic",
        imageUrl: IMAGE_URLS[c.id] ?? null,
        prepTime: c.method === "blended" ? 8 : c.difficulty === "medium" ? 5 : 3,
        ingredients: {
          create: c.ingredients.map((ci) => ({
            ingredientId: ci.id,
            amount: ci.amount,
            optional: ci.optional ?? false,
          })),
        },
      },
    });
  }

  const counts = {
    ingredients: await prisma.ingredient.count(),
    cocktails: await prisma.cocktail.count(),
    aliases: await prisma.ingredientAlias.count(),
  };
  console.log("Seed complete:", counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });